class ChatMessage {
  final int? id;
  final String userId;
  final String text;
  final bool isUserMessage;
  final DateTime? timestamp;
  
  // Added for playlist messages
  final String? playlistId;
  final String? playlistName;
  final bool isPlaylistMessage;

  ChatMessage({
    this.id,
    required this.userId,
    required this.text,
    required this.isUserMessage,
    this.timestamp,
    this.playlistId,
    this.playlistName,
    this.isPlaylistMessage = false,
  });

  factory ChatMessage.fromJson(Map<String, dynamic> json) {
    // Check if message contains playlist data
    final String message = json['message'] as String;
    String? extractedPlaylistId;
    String? extractedPlaylistName;
    bool isPlaylistMessage = false;
    String textToDisplay = message;
      // Parse for playlist format: [Created playlist 'playlist name'] message text
    final RegExp regExp = RegExp(r"\[Created playlist '(.*?)'\] (.*)");
    final match = regExp.firstMatch(message);
    
    if (match != null && match.groupCount >= 2) {
      isPlaylistMessage = true;
      extractedPlaylistName = match.group(1);
      textToDisplay = match.group(2) ?? '';
      
      // Extract playlist ID from metadata if available
      if (json['playlist_id'] != null) {
        extractedPlaylistId = json['playlist_id'] as String;
      }
    }

    return ChatMessage(
      id: json['id'],
      userId: json['user_id'],
      text: textToDisplay, // Use the extracted message without the playlist prefix
      isUserMessage: json['is_bot'] == false,
      timestamp: json['created_at'] != null 
          ? DateTime.parse(json['created_at'])
          : null,
      playlistId: extractedPlaylistId,
      playlistName: extractedPlaylistName,
      isPlaylistMessage: isPlaylistMessage,
    );
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> json = {
      // Note: 'id' is auto-generated by Supabase, so we don't need to include it here
      'user_id': userId,
      'is_bot': !isUserMessage,
      'created_at': timestamp?.toIso8601String(),
    };

    // Store the formatted message text for playlist messages
    if (isPlaylistMessage && playlistName != null) {
      json['message'] = "[Created playlist '$playlistName'] $text";
      if (playlistId != null) {
        json['playlist_id'] = playlistId;
      }
    } else {
      json['message'] = text;
    }
    
    return json;
  }
}