class ChatMessage {
  final int? id;
  final String userId;
  final String text;
  final bool isUserMessage;
  final DateTime? timestamp;

  ChatMessage({
    this.id,
    required this.userId,
    required this.text,
    required this.isUserMessage,
    this.timestamp
  });

  factory ChatMessage.fromJson(Map<String, dynamic> json) {
    return ChatMessage(
      id: json['id'],
      userId: json['user_id'],
      text: json['message'],
      isUserMessage: json['is_bot'] == false,
      timestamp: json['created_at'] != null 
          ? DateTime.parse(json['created_at'])
          : null,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      // Note: 'id' is auto-generated by Supabase, so we don't need to include it here
      'user_id': userId,
      'message': text,
      'is_bot': !isUserMessage,
      'created_at': timestamp?.toIso8601String(),
    };
  }
}